src/constraint_solver.rs, src/infer.rs, src/main.rs, src/parser.rs, src/syntax.rs, src/types.rs, tests/integration_test.rs
This PR also:
- introduces the idea of sub-typing by allow number literals to be used where numbers are expected (same for strings and booleans)
- looks up the id of type variables when applying substitutions
=> Infer Let and Op

Cargo.lock, Cargo.toml, src/infer.rs, src/lib.rs, src/parser.rs, src/syntax.rs
This is in preparation to add location information to the AST produced the by the parser.  This PR also introduces snapshot testing.
=> [parser]: update Expr enum to use structs

src/infer.rs, src/main.rs, src/parser.rs, src/syntax.rs
This PR modifies the parser to return a pair where the second element is the span.
TODOs:
-  [x] don't include trailing whitespace in identifiers
-  [x] don't include '=' in the span of the pattern in `Let` nodes (we weren't actually including the '=', but instead including both leading and trailing whitespace)
=> [parser]: Add location span data to parsed AST

src/codegen.rs, src/infer.rs, src/main.rs, src/parser.rs, src/syntax.rs, tests/codegen_test.rs, tests/integration_test.rs
This is so that we can parse multi-line programs and have top-level "let" declarations that don't have a body like the normal `let`.
=> Program parser

src/lexer.rs, src/lib.rs, src/main.rs, src/parser.rs, tests/codegen_test.rs, tests/integration_test.rs
This made differentiating between keywords and identifiers easier.
=> Add a lexing step before parsing tokens instead of chars

Cargo.lock, Cargo.toml, src/js_printer.rs, tests/codegen_test.rs
This PR also removes the use of `test_case` which ended up being more work to use there isn't a way to use inline snapshots with it.
=> [codegen]: generate 'exports', ensure all statements end with a single ';'

Cargo.lock, Cargo.toml, README.md, demo/app.tsx, package.json, src/main.rs, tests/codegen_test.rs, tests/integration_test.rs
`cricket` is ambiguous because it could mean the game or the insect.
=> Rename project to 'crochet'

src/constraint_solver.rs, src/infer.rs, src/main.rs, src/parser.rs, src/substitutable.rs, src/types.rs, tests/integration_test.rs
This PR fixes a couple of issues:
- improper application of remaining substitutions in `solver`
- inability of parser to parse more than one application in a row
- make output deterministic
The underlying issue for the third bullet point was that `.ftv()` returns a `HashedSet` which doesn't guarantee the iteration order.  This was remedied by sorting the qualifiers in `generalize()`.
=> Fix parse and infer errors

src/constraint_solver.rs, src/context.rs, src/infer.rs, src/substitutable.rs, src/ts/ast.rs, src/types.rs, tests/integration_test.rs
We'll likely want to re-add 'name' as an optional property in the future to model situations where developers have explicitly provided names for type parameters.  Since `crochet` currently doesn't support specifying types, it doesn't make sense to keep it around right now.
=> Remove 'name' property from TVar

src/ts/ast.rs, src/types.rs, tests/integration_test.rs
=> Use A, B, C, ... as type parameters

demo/app.tsx, src/js/ast.rs, src/js/builder.rs, src/js/printer.rs, src/parser.rs, tests/codegen_test.rs, tests/integration_test.rs
This PR also removes arrow function shorthand that was being used in some situations in order to make the js builder/printer simpler for now.  At some point in the future, shorthand will be re-enabled.
=> Codegen if-else

src/constraint_solver.rs, src/context.rs, src/infer.rs, src/ts/ast.rs, src/ts/convert.rs, src/types.rs, tests/integration_test.rs
This PR also removes the `TVar` struct since `id` now lives on the `Type` struct.  The old `Type` enum has been renamed to `TypeKind`.
=> Refactor Type so all types have ids

demo/app.tsx, src/context.rs, src/infer.rs, src/js/ast.rs, src/js/builder.rs, src/js/printer.rs, src/lexer.rs, src/parser.rs, src/syntax.rs, src/ts/ast.rs, src/ts/convert.rs, src/types.rs, tests/codegen_test.rs, tests/integration_test.rs
=> Basic object support

demo/app.tsx, src/constraint_solver.rs, src/context.rs, src/infer.rs, src/js/ast.rs, src/js/builder.rs, src/js/printer.rs, src/lexer.rs, src/parser.rs, src/syntax.rs, src/ts/ast.rs, src/ts/convert.rs, src/types.rs, tests/integration_test.rs
This PR also introduces `TypeKind::Alias`, _et al_ to model `Promise<T>` types.
=> Add support for async/await

src/constraint_solver.rs, src/context.rs, src/infer.rs, src/js/ast.rs, src/js/builder.rs, src/js/printer.rs, src/literal.rs, src/parser.rs, src/syntax.rs, src/ts/ast.rs, src/ts/convert.rs, src/types.rs
- have separate enums for value literals and type literals
- add structs for value literals
=> Reorganize literal AST nodes

src/ast/expr.rs, src/ast/jsx.rs, src/ast/mod.rs, src/parser.rs
We can now parse the following:
- opening and closing tags
- attributes that are strings or expressions
- text and expressions as children
=> Add support for parsing common JSX expressions

src/js/builder.rs, tests/codegen_test.rs
This doesn't actually transform the JSX to React.createElement() calls.  This will be done in a future PR using `swc_ecma_visit` and `swc_transforms_react`.
=> Generate JSX in output AST from input AST

demo/app.tsx, src/ast/expr.rs, src/infer/infer.rs
This doesn't type check the props yet.  We need to be able to import TypeScript .d.ts files first before we can even think about adding type checking for props.
=> Infer JSXElement

Cargo.lock, Cargo.toml, src/codegen/js.rs, tests/codegen_test.rs
The JavaScript we produce should be runnable in a browser without additional transforms.
=> Transform JSX to .createElement() calls in .js output

demo/app.tsx, src/infer/constraint_solver.rs, src/infer/context.rs, src/types.rs, tests/integration_test.rs
When widening types, the union of the two types should has the following characteristics:
- no duplicate types
- types should be sorted (based on their `id`)
- primitive types should subsume their corresponding literal types, e.g. `number | 5` -> `number`
- if there's only a single type in the union, then that type should be return instead of a union type
=> Normalize union types when widening

src/ast/literal.rs, src/ast/mod.rs, src/ast/types.rs, src/infer/infer.rs, src/parser.rs, src/snapshots/crochet__parser__tests__type_annotations-10.snap, src/snapshots/crochet__parser__tests__type_annotations-2.snap, src/snapshots/crochet__parser__tests__type_annotations-3.snap, src/snapshots/crochet__parser__tests__type_annotations-4.snap, src/snapshots/crochet__parser__tests__type_annotations-5.snap, src/snapshots/crochet__parser__tests__type_annotations-6.snap, src/snapshots/crochet__parser__tests__type_annotations-7.snap, src/snapshots/crochet__parser__tests__type_annotations-8.snap, src/snapshots/crochet__parser__tests__type_annotations-9.snap, src/snapshots/crochet__parser__tests__type_annotations.snap
=> Initial support for parsing explicit type annotations

src/codegen/d_ts.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/substitutable.rs, src/types.rs, tests/integration_test.rs
=> Use explicit type annotations to generate type constraints

src/ast/expr.rs, src/codegen/d_ts.rs, src/codegen/js.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/substitutable.rs, src/parser/decl.rs, src/parser/expr.rs, src/parser/snapshots/crochet__parser__tests__async_await-2.snap, src/parser/snapshots/crochet__parser__tests__async_await-3.snap, src/parser/snapshots/crochet__parser__tests__async_await-4.snap, src/parser/snapshots/crochet__parser__tests__async_await.snap, src/parser/snapshots/crochet__parser__tests__declarations-2.snap, src/parser/snapshots/crochet__parser__tests__declarations-4.snap, src/parser/snapshots/crochet__parser__tests__function_definition-2.snap, src/parser/snapshots/crochet__parser__tests__function_definition-3.snap, src/parser/snapshots/crochet__parser__tests__function_definition.snap, src/parser/snapshots/crochet__parser__tests__type_annotations-3.snap, src/parser/types.rs, src/types.rs
`args` should be used for application/calls and `params` for lambdas/functions.
=> Rename 'args' in lambda structs to 'params'

src/ast/expr.rs, src/ast/mod.rs, src/ast/types.rs, src/codegen/d_ts.rs, src/codegen/js.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/substitutable.rs, src/parser/expr.rs, src/parser/mod.rs, src/parser/snapshots/crochet__parser__tests__tuples-2.snap, src/parser/snapshots/crochet__parser__tests__tuples-3.snap, src/parser/snapshots/crochet__parser__tests__tuples.snap, src/parser/types.rs, src/types.rs, tests/integration_test.rs
This also updates `is_subtype` to handle checking tuple and union subtypes.
=> Add support for tuples

src/ast/expr.rs, src/ast/pattern.rs, src/infer/infer.rs, src/parser/decl.rs, src/parser/expr.rs, src/parser/jsx.rs, src/parser/mod.rs, src/parser/pattern.rs, src/parser/snapshots/crochet__parser__tests__blocks-2.snap, src/parser/snapshots/crochet__parser__tests__blocks-3.snap, src/parser/snapshots/crochet__parser__tests__blocks-4.snap, src/parser/snapshots/crochet__parser__tests__blocks.snap, src/parser/snapshots/crochet__parser__tests__declarations-3.snap, src/parser/types.rs, tests/codegen_test.rs, tests/integration_test.rs
Fixes #61.
This PR also allows blocks to be nested, e.g.
```
let result = {
let sum = {
let x = 5;
let y = 10;
x + y
};
sum
}
```
=> Replace 'in' with ';' when using let in expressions

src/ast/expr.rs, src/codegen/js.rs, src/infer/infer.rs, src/parser/expr.rs, src/parser/mod.rs, src/parser/snapshots/crochet__parser__tests__blocks-2.snap, src/parser/snapshots/crochet__parser__tests__blocks-3.snap, src/parser/snapshots/crochet__parser__tests__blocks-4.snap, src/parser/snapshots/crochet__parser__tests__blocks-5.snap, src/parser/snapshots/crochet__parser__tests__blocks-6.snap, src/parser/snapshots/crochet__parser__tests__blocks.snap, src/parser/snapshots/crochet__parser__tests__declarations-3.snap, tests/integration_test.rs
This allows the following code:
```
let foo () => {
let x = 5;
let y = 10;
console.log(x);
console.log(y);
x + y
}
```
This wasn't allowed before since all lines except for the last line in a block had to be `let <id> = ...` statements.
=> Allow multiple, non-let statements in a block

src/ast/pattern.rs, src/codegen/d_ts.rs, src/codegen/js.rs, src/infer/infer.rs, src/parser/mod.rs, src/parser/pattern.rs, src/parser/snapshots/crochet__parser__tests__destructuring-2.snap, src/parser/snapshots/crochet__parser__tests__destructuring-3.snap, src/parser/snapshots/crochet__parser__tests__destructuring-4.snap, src/parser/snapshots/crochet__parser__tests__destructuring-5.snap, src/parser/snapshots/crochet__parser__tests__destructuring.snap
There's still a lot to do in order to have restructuring working in terms of inference and codegen.  I'm going to split to work up into several PRs so that it's a bit easier to follow the changes.
=> Enable parsing of basic destructuring patterns.

src/codegen/d_ts.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/infer_mem.rs, src/infer/infer_pattern.rs, src/infer/mod.rs, src/infer/substitutable.rs, src/types.rs, tests/integration_test.rs
This PR includes some commented out code I was using to test it, but it uncovered an issue with how we're handling inference that will require adding more common fields to each inference type.  I want to change how inference types are structured so that it's easier to iterate on them without so much boilerplate.  This will happen in a series of PRs once this lands.
=> Rough in a more robust version of infer_pattern in its own file

src/codegen/d_ts.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/infer_mem.rs, src/infer/substitutable.rs, src/types.rs
This is the first step towards being able to specifying `widen_flags` on all types so that we can handle sub-typing more consistently.  The next PR will get rid of the inner structs that the variants are currently using.
=> Make Type a struct with a 'variant' field that's an enum

src/codegen/d_ts.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/infer_mem.rs, src/infer/substitutable.rs, src/types.rs
This simplifies the code a bunch since now we don't have destructure as many things in the inference code.
=> Remove a number of unnecessary type inference structs

src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/infer_mem.rs, src/infer/infer_pattern.rs, src/types.rs
In the future `Flag` will be used to determine how to resolve conflicting types during unification so it seems like it should have a more general name than `WidenFlag`.
This PR also adds a bunch of helper functions to Context to make it easier to construct `Type`s either with or without a flag.
=> Rename WidenFlag to Flag and add helper functions to Context

src/infer/constraint_solver.rs, src/infer/infer.rs, src/infer/infer_pattern.rs, src/infer/infer_type_ann.rs, src/infer/mod.rs, src/types.rs
This PR introduces a `Flag::SupertypeWins` to handle things like `let x: number = 5` where we want to allow the assignment of `5` to `x`, but we want the type of `x` to be `number`.  It also deduplicates the two versions of `type_ann_to_type()` that we had kicking around.
=> Refactor subtyping code to make better use of Flag

src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs
Now we're using `infer_patter()` for both `Let` and `Lambda`.
=> Update infer()'s lambda branch to use infer_pattern

src/infer/constraint_solver.rs, src/infer/infer_expr.rs, src/infer/infer_lambda.rs, src/infer/infer_mem.rs, src/infer/infer_prog.rs, src/infer/util.rs, src/types.rs, tests/integration_test.rs
This allows the same sort of partial destructuring that's supported in JavaScript, i.e.
```
let {x} = {x: 5, y: 10};
```
In the future we may want to require ellipsis when doing partial destructuring so as to communicate to the reader of the code whether there are other properties that are being ignored.
=> Allow partial object destructuring

src/parser/expr.rs, src/parser/mod.rs, src/parser/snapshots/crochet__parser__tests__if_else.snap, tests/integration_test.rs
This is so that the syntax for `if let` won't look that different from `if` when support is added for it in the future.
=> Don't require parens around the condition on 'if' statements

src/infer/constraint_solver.rs, src/infer/infer_expr.rs, src/infer/infer_prog.rs, src/types.rs, tests/integration_test.rs
This fixes an issue where `const add = (a, b) => a + b` was being inferred as `(number, number) => number` and then was accepting other types such as string when being called.
There are some situations where top-level types still need to be widened as in the following case:
```
let a = 5
let b = 10
let c = if cond { a } else { b }
```
In this situation `c` should have the type `5 | 10`.  This requires that `a` and `b` to be widened but only when used as the results of if-else blocks.
Because of this, this PR also introduces an `unfreeze()` function.
=> Freeze schemes so that top-level types can't be widened

src/ast/expr.rs, src/codegen/js.rs, src/infer/infer_expr.rs, src/parser/expr.rs, tests/integration_test.rs
This will be used to support `if` statements without an `else` block in the future as well as `if-let`.
=> Handle fucntions with an empty body

src/ast/expr.rs, src/codegen/js.rs, src/infer/infer_expr.rs, src/parser/expr.rs, src/parser/snapshots/crochet__parser__tests__if_else-2.snap, src/parser/snapshots/crochet__parser__tests__if_else.snap, tests/integration_test.rs
When there's a trailing `;` in a block, the type of that block's value will be inferred as `undefined`.
=> Make 'else' optional, allow trailing ';'

demo/app.tsx, demo/examples.js, src/ast/expr.rs, src/codegen/js.rs, src/infer/infer_expr.rs, src/infer/infer_pattern.rs, src/infer/infer_prog.rs, src/parser/expr.rs, src/parser/mod.rs, src/parser/snapshots/crochet__parser__tests__if_let.snap, src/types.rs, tests/integration_test.rs
This enables the following code to type-check and codeine:
```
let p = {x: 5, y: 10}
if let {x, y} = p {
let sum = x + y;
}
```
=> Implement `if-let` for non-refutable patterns

src/ast/pattern.rs, src/codegen/d_ts.rs, src/codegen/js.rs, src/infer/constraint_solver.rs, src/infer/infer_expr.rs, src/infer/infer_lambda.rs, src/infer/infer_pattern.rs, src/infer/infer_prog.rs, src/parser/mod.rs, src/parser/pattern.rs, src/parser/snapshots/crochet__parser__tests__if_let-4.snap, src/types.rs, tests/integration_test.rs
TODO:
There's a bunch of stuff this doesn't handle yet.  I'm going to introduce a utility function in a separate PR to help with determining if a type matches another type in the context of pattern matching and if-let.
=> Add support for 'is' refutable pattern

Cargo.lock, Cargo.toml, crates/crochet_thih/Cargo.toml, crates/crochet_thih/src/assump.rs, crates/crochet_thih/src/id.rs, crates/crochet_thih/src/lib.rs, crates/crochet_thih/src/lit.rs, crates/crochet_thih/src/pred.rs, crates/crochet_thih/src/prim.rs, crates/crochet_thih/src/scheme.rs, crates/crochet_thih/src/subst.rs, crates/crochet_thih/src/subtyping.rs, crates/crochet_thih/src/type.rs, crates/crochet_thih/src/unify.rs
THIH = Typing Haskell in Haskell.
This PR implements `mgu()` along with basic subtype handling.
=> Start alternative type inference implementation based on THIH

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs
The goal of this work is to remove the separate `run_solve()` step which solves a set of `Constraint`s.  Initially, I thought this would be easier to extend, but it ended up being more difficult because we loose information about what generated the constraints.  Calling `unify()` directly from `infer()` makes it easier to maintain this info which is critical in being able to allow sub-typing.
The next PR will focus on destructuring.
=> Start alternative inference algorithm within `crochet_infer` crate that doesn't use `Constraint`s

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
TODO:
This doesn't handle optional properties in objects.  I'll tackle that in a separate PR.
=> Add support for objects to non-cs algorithm

crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
TODO:
`if-let` using refutable patterns will have to wait for a future PR.
=> Add more tests to non-Constraint inference algorithm

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
=> Pattern matching of disjoint unions

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
This removes the need for the `Rel` enum and highlights the similarities between `unify` and `unify_subtype`.
=> rename is_subtype() to unify_subtype(), call unify_subtype() directly instead of calling it from unify()

crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/util.rs
=> Allow calls with args that are subtypes of params, enable partial application

crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__member_access-4.snap
This allows us to do things like: `foo().bar()` which weren't possible before.  This is an important step in our ability to support fluent APIs in the future.
=> Update parser to handle arbitrary interleaving of member access and function calls

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
This doesn't handle:
- inferring properties from use
- optional chaining
These will be handled in future PRs.
=> Basic member access

crates/crochet_ast/src/expr.rs, crates/crochet_codegen/src/js.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/pattern.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__objects-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__objects.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_annotations-4.snap
We currently use intersection types to model spread/rest at the type level.  This isn't actually the behaviour we want long term but it'll be good enough for now.
=> Infer rest/spread

crates/crochet/tests/codegen_test.rs, crates/crochet_ast/src/expr.rs, crates/crochet_codegen/src/js.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__template_literals.snap
TODO:
In order to support type inference of tagged template literals, we need to add support for arrays and rest params on functions.
=> Add support for tagged template literals

crates/crochet/tests/integration_test.rs, crates/crochet_ast/src/types.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-10.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-7.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-8.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-9.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations.snap, crates/crochet_parser/src/type_ann.rs
This PR make the following changes:
- enable parsing of array type annotations
- infer array types from array type annotations
- unify tuples with array types where each element in the tuple is a subtype of the array type's elements type
- codegens array types
=> Add support for array types

crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/util.rs
This isn't being used right now.  It's used in #162, but we can add something to `Variant::Object(...)` directly to track if an object type was generated from a member access.
=> Remove type flags

.github/workflows/ci.yml, crates/crochet/tests/fixture_test.rs
I doesn't really make sense to compute coverage on test files.
TODO:
=> Exclude all integration test files from coverage

crates/crochet/tests/integration_test.rs, crates/crochet_ast/src/types.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-10.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-11.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__type_annotations-8.snap, crates/crochet_parser/src/type_ann.rs
TypeScript requires params in function types to be named so we're going to do the same.
This PR also adds support for rest params in function types.
=> Require param names for function type annotations

Cargo.lock, crates/crochet_codegen/Cargo.toml, crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs
I've started adding codegen tests within the `crochet_codegen` crate.  In a future PR, I'll migrate all codegen tests out of the `crochet` crate into `crochet_codegen`.
=> Add tests for codegen of (tagged) template literals

crates/crochet/tests/codegen_test.rs, crates/crochet/tests/integration_test.rs, crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs
In a number of places we were using IIFEs to handle expressions that are normally statements in JavaScript.  Unfortunately, this was introducing extra entries into the call stack which would undoubtedly lead to confusing later on when debugging code.  This removes the unnecessary IIFEs.
=> Get rid of extra call stack entries that are introduced by `let`, `if-else`, and `match` in codegen

crates/crochet/tests/integration_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/types/scheme.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/util.rs
It isn't being used anywhere anymore.  infer_expr.rs generate union types when inferring `IfElse` and `Match` expressions by inferring the result type of each arm and computing the union of those types.
=> remove .frozen field from types

crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs
Codegen for `LetExpr` was ignoring the `alt` field.  This PR fixes that along with an issue where some of the temp variables were being used incorrectly.
=> Fix if let else codegen

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/crochet/tests/integration_test.rs, crates/crochet_ast/src/literal.rs, crates/crochet_ast/src/types.rs, crates/crochet_codegen/Cargo.toml, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_dts/Cargo.toml, crates/crochet_dts/src/lib.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-9.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__type_ann__tests__misc_type_annotations-2.snap, crates/crochet_parser/src/type_ann.rs
This PR makes the following changes:
- updates swc_* dependencies
- adds `mutable` field to `TProp`
- parses properties and methods on some interfaces from lib.es5.d.ts (String, Number, Boolean, etc.)
I'll continue filling in the gaps in future PRs.
=> Parse some parts of .d.ts files and infer appropriate Crochet types

crates/crochet_ast/src/lib.rs, crates/crochet_dts/src/lib.rs
Two tests had the same name so tarpaulin was only reporting coverage from one of those test case.
=> Fix crochet_dts test coverage reporting

Cargo.lock, crates/crochet/src/lib.rs, crates/crochet/tests/fixture_test.rs, crates/crochet/tests/integration_test.rs, crates/crochet_dts/Cargo.toml, crates/crochet_dts/src/lib.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs
`parse_dts` returns a Context and `infer_prog()` now takes a Context as parameter instead of creating its own.
=> Connect parse_dts() to infer_prog()

crates/crochet_codegen/src/d_ts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/pattern.rs
This allows us to pass `_` as args to function calls.  This results in args not being passed for those params and the result of the call the partial application of the non-`_` params, e.g.
```
let add = (a, b, c) => a + b + c;
let add_mid_5 = add(_, 5, _); // equivalent to (a, c) => a + 5 + c;
```
=> Rework partial application to use placeholders

crates/crochet_codegen/src/d_ts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__function_application-6.snap
This is a stepping stone towards having named functional params in types as well as optional and mutable params.
=> Replace .is_call with App type variant

crates/crochet/tests/integration_test.rs, crates/crochet/tests/pass/combinators.d.ts, crates/crochet_ast/src/pattern.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs
TODO:
```
let bar = ([x, y]: [number, number]) => x + y;
let baz = ({x, y}: {x: number, y: number}) => x + y;
```
=> Introduce TParam and use it maintain original param names in types

crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs
This handles destructured function params and removes some dead code from d.ts code generation.
=> Handle more patterns in codegen

crates/crochet/tests/integration_test.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs
Now that we're creating union types when inferring `IfElse` and `Match` expressions we no longer need `id`s on the `Type` struct, it's enough to have them only on type variables.  This allows us to simplify the code greatly.  In a future PR we can get rid of the builder methods on `Context` since we only need `Context` when creating new type variables now.
=> Replace `Variant::` with `Type::`

crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs
`fresh_var()` and `fresh_id()` are the only builder methods that need to appear on `Context`.
=> Remove most of the builder methods from Context

webpack.config.js
This still requires making a change to a .ts(x) file in demo/ before the changes will appear in the browser, but at least the .wasm bundle is being rebuilt in response to changes in the crates' source code now.
=> Update WasmPackPlugin to watch all crates

Cargo.lock, crates/crochet_ast/Cargo.toml, crates/crochet_ast/src/expr.rs, crates/crochet_ast/src/jsx.rs, crates/crochet_ast/src/lib.rs, crates/crochet_ast/src/lit.rs, crates/crochet_ast/src/prim.rs, crates/crochet_ast/src/type_ann.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/Cargo.toml, crates/crochet_types/src/lib.rs, crates/crochet_types/src/lit.rs, crates/crochet_types/src/prim.rs, crates/crochet_types/src/type.rs
This is necessary in order for us to add `inferred_type` fields to AST nodes in `crochet_ast`, otherwise there'd be a cyclic dependency between crates which isn't allowed.
This PR also renames a few structs to make it easier to differentiate between structs from `crochet_ast` and `crochet_types`.
=> Remove crochet_ast dep from crochet_types

crates/crochet/tests/integration_test.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/lib.rs
Having a vector of `Scope`s within the `Context` struct will allow us to track which symbols were added to which scopes.  This information will help us to determine which symbols were added by a module as opposed to being in scope because they were imported from another module or because they're globals.
=> Add multiple scopes to Context

crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/scheme.rs, crates/crochet_types/src/type.rs
=> Refactor parse_dts.rs

demo/examples.js
=> Give function params names in function overloading example

crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/type.rs, demo/app.tsx
It adds a bunch of complexity without much value.  It's still possible to create partially applied functions without special syntax by creating a new function that calls an existing function, e.g.
```
let add = (a, b) => a + b
let add5 = (b) => 5 + b
```
=> Remove partial application

crates/crochet_codegen/src/js.rs, crates/tree_sitter_crochet/corpus/expressions.txt, crates/tree_sitter_crochet/corpus/semicolon_insertion.txt, crates/tree_sitter_crochet/corpus/statements.txt, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/grammar.js, crates/tree_sitter_crochet/src/grammar.json, crates/tree_sitter_crochet/src/node-types.json
This PR also updates a number of statements that were using `field("body", $.statement)` to use `field("body", $.statement_block)` instead, e.g. `while`, `for`, etc.
TODO:
=> Add support for do-expressions

crates/tree_sitter_crochet/corpus/expressions.txt, crates/tree_sitter_crochet/corpus/statements.txt, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/grammar.js, crates/tree_sitter_crochet/src/grammar.json, crates/tree_sitter_crochet/src/node-types.json
This will allow us to write things like:
```
const foo = (): number => {
let x = 5;
let y = 10;
x + y
}
```
The last line in this example is `expression` instead of an `expression_statement`.
The last line can be either an `expression` or an `expression_statement`.  In the case of the former, that value will be used as the value for the block (and in the case of functions/methods it will be the return value).  If is the latter, then the value of the block will be `undefined` effectively ignoring the value of the `expression_statement`.
=> Update statement_block to allow a trailing expression

crates/crochet_tree_sitter_parser/src/lib.rs, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__if_let-2.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__if_let.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__pattern_matching-2.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__pattern_matching-3.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__pattern_matching-4.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__pattern_matching.snap, crates/tree_sitter_crochet/corpus/refutable_patterns.txt, crates/tree_sitter_crochet/grammar.js, crates/tree_sitter_crochet/src/grammar.json, crates/tree_sitter_crochet/src/node-types.json
=> Add support for parsing 'match' expressions to AST

crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/lam.rs, crates/crochet_types/src/lib.rs, crates/crochet_types/src/obj.rs, crates/crochet_types/src/qualified.rs, crates/crochet_types/src/scheme.rs, crates/crochet_types/src/type.rs
This allows us to redefine `Scheme` as
```
type Scheme = Qualified<Type>
```
and `TCall` as
```
type TCall = Qualified<TLam>
```
=> Introduce Qualified<T> struct to help dedupe code a bit

crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/unify.rs
This allow object types with indexers to be indexed and object types with callable to be called.  There are some issues with generic indexers/callables, but those will be handled in a separate PR since it requires a substantial changes to how generics are handled.
=> Unify indexers and callables

crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/type.rs
`type_params` is now being used only for generic type parameters whereas alias types (which are actually type references) are passed type args.  We should probably just rename `TAlias` to `TypeRef` to more closely align with TypeScript.
=> Rename .type_params to .type_args on TAlias

crates/crochet_cli/tests/integration_test.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs
This is necessary for `Promise<T>` whose definition is spread across multiple .d.ts files.
=> Handle merging generic interfaces correctly

crates/crochet_dts/src/lib.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/util.rs
`replace_aliases()` was difficult to use because there was a lot of setup that had to be done outside of the function before calling it.  All of that complexity has been moved inside `replace_aliases()`.
This PR also updates how we parse methods on interfaces in .d.ts.  We now handle type params on methods.
=> Simplify the use of `replace_aliases()`

crates/crochet_ast/src/type_ann.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-7.snap, crates/crochet_types/src/keyword.rs, crates/crochet_types/src/type.rs
This is a pre-req for supporting mapped types since many of the utility types defined using mapped types make use of `keyof`.
=> Add support for `keyof` operator

crates/crochet_ast/src/type_ann.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-8.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-9.snap
This PR also does some renaming of functions in infer_type_ann.rs and updates their signatures to require a mutable `Context`.
=> Implement 'typeof' type query operator

crates/crochet_ast/src/type_ann.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-9.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-11.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-4.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-8.snap, crates/crochet_types/src/obj.rs
This allows us to define object types in Crochet that include indexers.
=> Parse indexers in object types annotations

crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/snapshots/crochet_infer__tests__infer_ident_inside_lam.snap, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/lam.rs, crates/crochet_types/src/obj.rs, crates/crochet_types/src/type.rs
Really any type can contain type variables and thus could become qualified as a result of generalization (if it appears at the top-level).  This is basically a reformulation of the `Scheme` type that we had before.  The main difference is that qualified types are types and as such can appear within a `Type` data structure whereas `Scheme`s could only appear at the top.  The reason we couldn't use `Scheme` is that TypeScript interfaces can be qualified, but also contain other types which themselves are qualified, e.g. a method that is generic.  In these situations, we don't want to hoist type params from every generic method up to live on the interface itself.  `Type::Qualified` addresses this situation by allowing type params to be specified at different levels with in a type.
=> Replace `type_params` on Type::Lam and Type::Object with Type::Qualified wrapper

crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/util.rs
This a work-in-progress.  Before this can be completed we need to support type qualifiers on all types not just function and object types.  I'll do that work in a separate PR and then rebase this one.
=> Indexed access should always return T | undefined

crates/crochet_cli/tests/integration_test.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/assump.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs
- rename `scheme` to `t` or `type`
- update `infer_prog` to call `close_over()` on the result from `infer_type_ann`
- merge some of the functions in infer_type_ann.rs
- replace `super::` with `crate::`
- other small tweaks
=> Simplify crochet infer

Cargo.lock, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/Cargo.toml, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/obj.rs, crates/crochet_types/src/type.rs
=> Constrained Generics

crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs
=> Fix miscellaneous generics bugs

crates/crochet_ast/src/type_ann.rs, crates/crochet_cli/tests/integration_test.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_types/src/type.rs, crates/tree_sitter_crochet/corpus/expressions.txt, crates/tree_sitter_crochet/corpus/tsx/types.txt, crates/tree_sitter_crochet/grammar.js, crates/tree_sitter_crochet/yarn.lock
Updates to the unification algorithm will happen in a separate PR.
=> Parse and codegen `mut`/`readonly`

Cargo.lock, crates/crochet_ast/Cargo.toml, crates/crochet_codegen/Cargo.toml, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_dts/Cargo.toml
This fixes an issue with the `readonly` modifier not being emitted from `TsIndexSignature` nodes.  Also, more things are boxed now so that required a few changes to d_ts.rs.
=> Upgrade swc depedencies

crates/crochet/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__top_level_parse_error.snap, demo/wasm.ts
=> Parser error handling

crates/crochet_cli/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_parser/src/lib.rs
This fixes #298.  This PR also makes the following changes:
- fixes an issue with inferring rest patterns (we were using the wrong identifier)
- object patterns as type params must destructure all properties
=> Ensure that the .init field of Expr::Let is being inferred

crates/crochet_ast/src/keyword.rs, crates/crochet_ast/src/lit.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/snapshots/crochet_infer__tests__infer_ident_inside_lam.snap, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/lam.rs, crates/crochet_types/src/type.rs
This is preparation for adding provenance information to the `Type` struct which is necessary for assigning literal subtype types to mutable variables, e.g. `let air: mut number[] = [1, 2, 3]`.  These will be handle in separate future PRs.
=> Rename current Type enum to TypeKind and introduce Type struct

crates/crochet_ast/src/common/binding.rs, crates/crochet_ast/src/types/keyword.rs, crates/crochet_ast/src/types/lam.rs, crates/crochet_ast/src/types/lit.rs, crates/crochet_ast/src/types/obj.rs, crates/crochet_ast/src/types/pat.rs, crates/crochet_ast/src/types/type.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs
`BTreeSet` has a stable ordering and `PartialOrd` and `Ord` traits can both be derived automatically for structs and enums.  The order of enum variants is based on the order they appear in the code.
=> Replace uses of HashSet with BTreeSet

Cargo.lock, crates/crochet_ast/Cargo.toml, crates/crochet_ast/src/types/lam.rs, crates/crochet_ast/src/types/type.rs, crates/crochet_ast/src/values/keyword.rs, crates/crochet_ast/src/values/lit.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/snapshots/crochet_infer__tests__infer_ident_inside_lam.snap, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs
It's currently set to `None`, but we'll want to set it to the assigned expression if it's a literal, object, or tuple.  This is to support assigning these things to mutable types.  I'll tackle this in the next PR since the changes in this one were pretty mechanical, but the other changes won't be.
=> Add .provenance field to Type

crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-12.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-13.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-9.snap, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/grammar.js
Replaces the `readonly` modifier.
=> Update parser to handle 'mut' modifier on properties

crates/crochet_ast/src/types/mod.rs, crates/crochet_ast/src/types/provenance.rs, crates/crochet_ast/src/types/type.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/snapshots/crochet_infer__tests__infer_ident_inside_lam.snap, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs
This allows us to set `.provenance` to be either an `Expr` or a `Type`.  This allows us to track provenance after applying a `Subst` to a type.
=> Add Provenance enum and update .apply() to use it

crates/crochet_ast/src/values/ident.rs, crates/crochet_ast/src/values/pattern.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-10.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-11.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-12.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-13.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-9.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__function_definition-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__if_let.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__pattern_matching-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__pattern_matching.snap, crates/tree_sitter_crochet/corpus/destructuring.txt, crates/tree_sitter_crochet/corpus/expressions.txt, crates/tree_sitter_crochet/corpus/refutable_patterns.txt, crates/tree_sitter_crochet/corpus/statements.txt, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/corpus/tsx/functions.txt, crates/tree_sitter_crochet/corpus/tsx/types.txt, crates/tree_sitter_crochet/grammar.js
This is going to allow us to specify which binding identifiers we want to be mutable when destructuring values as part of variable declarations and parameters in functions, e.g.
```
let {a, mut b} = obj;
let foo = ({p, q: mut r}) => { ... }
let [x, mut y, z] = arr;
```
This avoids having to do multiple destructurings if you want some variables to be `const` and others to be `let` like you do now in JS/TS, e.g.
```
const {a} = obj;
let {b} = obj;
```
This PR also updates the tree-sitter grammar to disallow the use of LHS expressions as patterns.
TODO:
NOTE: We still have to handle shorthand props and assignment props.  I'll do this in a separate PR because I want to rework how we model object properties in patterns in the AST to be more like what babel does which is a lot simpler than what …
=> Allow all binding identifiers to be mutable

crates/crochet/src/lib.rs, crates/crochet_cli/tests/integration_test.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/type_error.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/unify_mut.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/parse_error.rs, crates/tree_sitter_crochet/bindings/rust/build.rs
The reason for adding structs, is so that we can introduce [error_stack](https://docs.rs/error-stack/latest/error_stack/). This will be done in a followup PR.
=> Add ParseError and TypeError structs

Cargo.lock, crates/crochet/Cargo.toml, crates/crochet/src/compile_error.rs, crates/crochet/src/lib.rs, crates/crochet_cli/Cargo.toml, crates/crochet_cli/tests/integration_test.rs, crates/crochet_dts/Cargo.toml, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/Cargo.toml, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/type_error.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/unify_mut.rs, crates/crochet_parser/Cargo.toml, crates/crochet_parser/src/lib.rs
In a future PR, I'll update the error reporting so that we can report multiple parse errors or multiple type errors.
=> Adopt error-stack for error reporting

.github/workflows/ci.yml
This also updates ci.yml to only run if there are changes to .rs, .js, or .crochet files.  We really don't need to be running the checks for PRs that only modify .md files.
=> Update triggers in ci.yml so that checks will run on PRs from contributors

design/mvp/03_type_safety.md
Fix typo in `as const` example
=> Fix typo in `as const` example

design/mvp/02_expressions.md
Fix typo: "changed" -> "chained"
=> Fix typo in 02_expressions.md

crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/type_error.rs
This has implications for parametric function which accept `mut T`, but TBH, doing so doesn't make sense without constrained polymorphism so it's probably okay to disallow `mut string`, `mut boolean`, etc.
=> Disallow mutable primitives and tuples

crates/crochet/src/diagnostics.rs, crates/crochet/tests/errors/incompatible_types.crochet, crates/crochet/tests/errors/incompatible_types.error, crates/crochet/tests/errors/rest_param.crochet, crates/crochet/tests/errors/rest_param.error, crates/crochet/tests/pass/rest_param.crochet, crates/crochet/tests/pass/rest_param.d.ts, crates/crochet/tests/pass/rest_param.js, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs
If there were type mismatches between multiple args and params in a function call, we were only reporting the first mismatch.  With this PR we now report all mismatches.
This PR also deduplicates some of the unification logic between calls to functions with a rest param and those without.
=> Report all errors unifying args and params

crates/crochet_cli/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__rust_style_functions-2.snap
This PR is an attempt to minimize the difference between a trailing expression vs trailing statement in a block.  When the last line in a block is followed by a `;` it's a statement and when it isn't then it's an expression.  In both cases, the inferred type of the block is the type of the last statement/expression.  The reason for not requiring `undefined;` when there's nothing to "return" is that this would require adding this to all blocks where that's the case including functions, try-catch, etc.
Since an `if` (without an `else`) could appear at the end of a block, we need to allow that an infer a sensible value for this it.  This PR does this, inferring its type as `T | undefined` if the consequent's value is `T`.
Variable declarations are now allowed at the end of a block.  While …
=> Treat the last statement in a block the same as if it were an expression

crates/crochet/tests/fixture_tests.rs, crates/crochet/tests/pass/mapped_types.crochet, crates/crochet/tests/pass/mapped_types.d.ts, crates/crochet/tests/pass/mapped_types.js, crates/crochet_ast/src/types/type.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/mapped_type.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/type_error.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_infer/src/visitor.rs
TODO:
- ~update parser to handle mapped types in the source code~ I'm going to do this in a separate PR since most of the code to implement this will be largely unrelated to what's in this PR which is already quite large.
=> Mapped types

crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/unify.rs
This is a quick fix to handle any generics that slip through the cracks.  It's likely that we forgot to instantiate properties after looking them up on an object.  I'll look into making that change later.
=> Instantiate any types that are still generic in unify()

crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/tests/codegen_test.rs
We were using the `readonly` modifier for all array and tuple types even when the type as mutable.  This PR fixes that.
=> Fix .d.ts code generation of mutable types

crates/crochet_ast/src/types/type.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/conditional_type.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/mapped_type.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_infer/src/visitor.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-8.snap
TODO:
- ~automatically determine which type param is being used as the `check_type`~
- ~more test cases (including nested conditional types)~
I'm going to tackle these in a followup PR once I have a more generate `expand_type` function that interleaves `key_of`, `compute_mapped_type`, and `compute_conditional_type`.
=> Conditional types

crates/crochet_ast/src/types/obj.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer_type_ann.rs
Index key types are much more constraint than function param types.  They should have their own data structure to reflect this.
=> Stop using TFnParam for index keys

crates/crochet/tests/pass/conditional_types.crochet, crates/crochet/tests/pass/conditional_types.d.ts, crates/crochet/tests/pass/conditional_types.js, crates/crochet_infer/src/lib.rs, crates/tree_sitter_crochet/corpus/tsx/types.txt, crates/tree_sitter_crochet/grammar.js
=> Make the conditional_type have right-to-left precendence in grammar.js

crates/crochet/tests/pass/new_expressions.crochet, crates/crochet/tests/pass/new_expressions.d.ts, crates/crochet/tests/pass/new_expressions.js, crates/crochet_ast/src/types/keyword.rs, crates/crochet_ast/src/types/provenance.rs, crates/crochet_ast/src/values/expr.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__new_expression-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__new_expression.snap
=> Add support for 'new' expressions

Cargo.lock, crates/crochet/Cargo.toml, crates/crochet/src/compile_error.rs, crates/crochet/src/diagnostics.rs, crates/crochet/src/lib.rs, crates/crochet/tests/fixture_tests.rs, crates/crochet_cli/Cargo.toml, crates/crochet_cli/tests/integration_test.rs, crates/crochet_dts/Cargo.toml, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/Cargo.toml, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/type_error.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/unify_mut.rs, crates/crochet_parser/Cargo.toml, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/parse_error.rs
The reason for this is that error-stack doesn't support cyclic data types b/c they aren't thread safe.  Additionally, we're going to need to change error handling quite significantly if we want to support reporting warnings or allowing unification to continuing after reporting errors with function call param/args mismatches.
TODO:
=> Remove all uses of error-stack

crates/crochet_ast/src/types/type.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_infer/src/write_report.rs
This reduces the number of `Type`s we have to create and simplifies some of the code in substitutable.rs.  It does complicate some of the other code since in some places we have to clone a `Type` now before calling `.apply()` on it to prevent unwanted mutation.
=> Refactor .apply() to mutate its receiver

.github/workflows/ci.yml
This PR is based on https://blog.rng0.io/how-to-do-code-coverage-in-rust, but opts not to use `xtask`.
=> Use grcov to generate lcov report

Cargo.lock, Cargo.toml, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/unify_mut.rs, crates/crochet_infer/src/util.rs, crates/crochet_lsp/Cargo.toml, crates/crochet_lsp/src/main.rs, crates/crochet_parser/src/lib.rs, packages/vscode-crochet/package.json, packages/vscode-crochet/src/extension.ts, packages/vscode-crochet/yarn.lock
This PR implements a very simple LSP that responds to `HoverRequest`s.  As part of the request, it parses the code in the file from the hover request was made from and does type inference.  It responds with a generic "Hello world!" string.  In the future we'll determine the type for the symbol at the given cursor location, but we need #405 before that can happen.
One thing that took me a while to figure out what was that all of the `println!()`s that I had scattered around were interfering with the stdio communication between the LSP server and the client.  This PR changes all of them to be `eprintln!()`s so that their output goes to stderr instead.
I did some profiling and while each request takes about 75~100ms, the majority of the time is taken up by reading/parsing of lib.es5.d.ts. …
=> Boostrap LSP

crates/crochet_ast/src/values/expr.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/snapshots/crochet_infer__tests__infer_ident_inside_lam.snap, crates/crochet_lsp/src/main.rs, crates/crochet_lsp/src/visitor.rs
TODO:
I'll write some unit tests in a separate PR since this will likely require some refactoring and I'd like to get the current changes landed.
- press F5 to run the VSCode extension in a new instance of VSCode
- open a few different .crochet files
- hover over different things in each file, see the types displayed
- making some edits without saving
- hover over the new code, see the types displayed
=> Initial implementation of hover to show inferred type in LSP

crates/crochet_ast/src/types/type.rs, crates/crochet_ast/src/values/keyword.rs, crates/crochet_ast/src/values/type_ann.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/src/util.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_class.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/scheme.rs, crates/crochet_infer/src/snapshots/crochet_infer__scheme__tests__instantiate_scheme_with_constrained_type_param.snap, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_infer/src/visitor.rs, crates/crochet_lsp/src/semantic_tokens.rs, crates/crochet_lsp/src/visitor.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__conditional_types-2.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__conditional_types-3.snap
TODO:
It turned out that this wasn't actually the way to implement support for `infer`.
- ~update `expand_conditional_type()` to add a new scope~
- ~update `expand_type` to insert a type binding when handling `TypeKind::InferType`~
=> Add support for 'infer' type

crates/crochet/tests/pass/new_expressions.d.ts, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs
In keeping with Crochet's "immutable by default" philosophy, this PR updates Crochet to infer `new` expressions as immutable.  We allow `new` expressions to be assigned to l-values that are type as immutable (similar to what we do for array and object literals), but all other immutable references may not be used as mutable ones.
=> Infer new-expressions as immutable

Cargo.lock, crates/crochet_infer/Cargo.toml, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/expand_type.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_class.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/scheme.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/update.rs, crates/crochet_infer/src/util.rs, crates/crochet_interop/src/parse.rs
I want to try using `im` for the hash maps in `Context`, but in order to do so, `.apply()` can't be mutating.
=> Switch back to using immutable references in unify() and infer_expr()

crates/escalier_infer/src/assump.rs, crates/escalier_infer/src/context.rs, crates/escalier_infer/src/expand_type.rs, crates/escalier_infer/src/infer_class.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_type_ann.rs, crates/escalier_infer/src/scheme.rs, crates/escalier_infer/src/substitutable.rs, crates/escalier_infer/src/unify.rs, crates/escalier_infer/src/util.rs
This should hopefully reduce memory consumption.  In a future PR, I'll update `Context` to store a single `Scope` instead of a stack of `Scope`s.
Fixes #455.
=> Use im HashMap in escalier_infer instead of the one from std::collections

crates/escalier_codegen/src/d_ts.rs, crates/escalier_codegen/src/js.rs, crates/escalier_infer/src/scheme.rs, crates/escalier_infer/src/unify.rs
I also changed some `&Option<T>`s to `Option<&T>`s.
=> Dedupe code in js codegen and other misc cleanup

crates/escalier_cli/tests/integration_test.rs, crates/escalier_codegen/tests/codegen_test.rs, crates/escalier_infer/src/checker.rs, crates/escalier_infer/src/context.rs, crates/escalier_infer/src/expand_type.rs, crates/escalier_infer/src/infer_class.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_prog.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/infer_type_ann.rs, crates/escalier_infer/src/scheme.rs, crates/escalier_infer/src/unify.rs, crates/escalier_infer/src/util.rs, crates/escalier_interop/src/parse.rs, crates/escalier_interop/tests/integration_test.rs
This allows our type inference code to be simplified greatly since `current_scope` can be accessed via `self` instead of having to pass `ctx` as a param to every function that needed it.  Many functions didn't need it, but we were passing it anyways because something else that we called needed it downstream.
=> Add current_scope/parent_scopes to Checker struct

crates/escalier/src/compile_error.rs, crates/escalier/src/diagnostics.rs, crates/escalier/src/lib.rs, crates/escalier/tests/errors/incompatible_types.error, crates/escalier/tests/fixture_tests.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_infer/src/checker.rs, crates/escalier_infer/src/diagnostic.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/lib.rs, crates/escalier_infer/src/unify.rs, crates/escalier_interop/src/parse.rs
This is the first recoverable diagnostic.  I'll add more in future PRs.
=> Add recoverable diagnostic for assigning the wrong type to a variable decl with a type annotation

crates/escalier/src/diagnostics.rs, crates/escalier/tests/errors/incompatible_types.error, crates/escalier/tests/errors/rest_param.error, crates/escalier/tests/fixture_tests.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_infer/src/checker.rs, crates/escalier_infer/src/diagnostic.rs, crates/escalier_infer/src/expand_type.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/lib.rs, crates/escalier_infer/src/type_error.rs, crates/escalier_infer/src/unify.rs, crates/escalier_interop/src/parse.rs, crates/escalier_interop/tests/integration_test.rs
This allows us to report recoverable errors.
=> Create separate error reports for each expression

Cargo.lock, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs
This PR also:
- renames a few more `operator`s to `constructor`s
- gets rid of static definitions of `INTEGER` and `BOOLEAN`
- removes unnecessary dependencies
=> Update test_env() to only reuse types when necessary

crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/literal.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs
This PR simplifies the data structure used for literals and adds support for using `true` and `false` literals as subtypes of `boolean`.  We could try defining `boolean` as `true | false`.  This would remove at least one special case in `unify()`, but we need type aliases for that.  I'll add those in a future PR.
=> Improve literal types

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs
TODO:
In a future PR, add support for statements.
=> Add support for mutually recursive functions

Cargo.lock, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/env.rs, crates/escalier_hm/src/errors.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs
This type kind didn't make much sense.  Instead, having a separate `unify_call()` function to handle unifying calls with different things such as objects with callables or type constructors that might be callable makes more sense.
=> Get rid of TypeKind::Call and add support for objects and tuples

crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/types.rs
In a future PR I'll try to introduce type params to escalier_hm's `Function` type and remove the need for passing `non_generic` around.
=> Remove Namer

Cargo.lock, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs
The generational arena is a better than `Vec<usize>` because it solves the ABA problem when updating a tree/graph.  See https://docs.rs/generational-arena/latest/generational_arena/index.html#what-why for details.
=> Replace Vec<usize> with generational_arena

crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs
This PR update the behaviour of generic functions in escalier_hm to be more like that of escalier_infer.  In particular, we generalize functions at the top-level by replacing type variables with type references.  The function also gains type params that correspond to the type variables that were replaced.
=> Generalize top-level functions and instantiate type references

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs
This PR also updates the tests in lib.rs by renaming `a` to `arena` and removing all of the predefined functions from the environment.  Functions like `zero`, `pred`, `times` are inlined in tests (or redefined where appropriate).
=> add support for binary and unary operators in escalier_hm

crates/escalier_cli/tests/integration_test.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/unify.rs
We weren't instantiating the function types which meant that the type params weren't being converted to the appropriate type variables in the function definition.
=> Fix I = S(K)(K) identity in escalier_hm

crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_pattern.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs
Having a separate type kind to model array/tuple rest makes unifying a bunch of different situations much easier.
=> Add TypeKind::Rest to escalier_hm

crates/escalier_hm/src/ast/expr.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/parser/expr.rs
- `==` and `!=` can be used with any types now, but both operands must have the same type
- `&&` and `||` have been added, their operands must both be boolean values
=> Improve logic operators in escalier_hm

crates/escalier_hm/src/infer.rs, crates/escalier_hm/tests/integration_test.rs
This fixes a long-standing problem where the following code wouldn't error:
```
let add = <T>(a: T, b: T) => {
return a + b;
};
```
This issue still exists in `escalier_infer`, but it's fixed now in `escalier_hm` which is what we'll eventually be moving to.
=> Use type param constraints when inserting params into sig_ctx

crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/func_param.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/pattern_parser.rs, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/type_ann_parser.rs
This is necessary before we attempt to make the lever return an iterator.
=> Remove lookahead option from lexer.peek()

crates/escalier_parser/src/expr.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/jsx_parser.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/scanner.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_functional_component.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_functional_component_with_fragment.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_literals-5.snap, crates/escalier_parser/src/snapshots/escalier_parser__jsx_parser__tests__parse_jsx_props_dot_children.snap
Up til now we've only be able to parse JSX in isolation.  This PR will make it possible to parse JSX within larger expressions and statements.
TODO:
=> Parse JSX within expressions

crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_do_expr.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_destructuring.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_destructuring_and_type_annotation.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_optional_params.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_params.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_type_annotations.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_multiple_application.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_param_destructuring.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_pattern_matching.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_catch.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_catch_finally.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_finally.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_conditionals-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_conditionals.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_one_liners-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_one_liners.snap, crates/escalier_parser/src/stmt_parser.rs
This will make inline usage of things like `if-else` more ergonomic, e.g.
```
if (cond) { x } else { y }
```
One-liners look a little weird, e.g.
```
foo() bar() baz()
```
instead of
```
foo(); bar(); baz()
```
but that's okay because I don't really use one-liners.
=> Drop the requirement that statements need to be separated by semi-colons

crates/escalier_parser/src/expr.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_async_await.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_callback.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_func_with_type_params-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_func_with_type_params-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_func_with_type_params.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_destructuring.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_destructuring_and_type_annotation.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_optional_params.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_params.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_with_type_annotations.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_functional_component.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_functional_component_with_fragment.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_generator_function.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_lambdas-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_lambdas-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_lambdas.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_param_destructuring-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_param_destructuring.snap, crates/escalier_parser/src/snapshots/escalier_parser__parser__tests__lex_nested_template_strings_complex.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_lambda-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_lambda.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_let_fn_with_fn_type.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_one_liners-2.snap
I'm punting on parsing type args on function calls for now since this requires back tracking and error handling.
=> Parse type params in functions

crates/escalier_parser/src/expr.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/scanner.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_async_await.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_call_expr.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_callback.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_func_calls_with_type_args-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_func_calls_with_type_args.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_call-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_call-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_function_call.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_multiple_application.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_optional_chaining-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_catch.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_catch_finally.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_try_finally.snap, crates/escalier_parser/src/snapshots/escalier_parser__parser__tests__lex_nested_template_strings_complex.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_conditionals-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_new_line_inference-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_one_liners-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_one_liners.snap
This required storing (and restoring) the state of the parser when to resolve conflicts between expression involving less-than and function calls with explicit type args.
=> Parse type args in function calls

.vscode/settings.json, crates/escalier_ast/src/type_ann.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_object_type_all_sig_types.snap, crates/escalier_parser/src/type_ann_parser.rs
TODO:
- etc.
I'm going to move (object, function) unification and updating `simplify_intersection` in future PRs
=> Adding for getters, setters, and callables

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/provenance.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/visitor.rs
This should come in handy debugging issues with the im(mutable) binding work.  Later it can be used for error reporting and other diagnostics.
=> Add provenance to Type from TypeAnn and Expr AST nodes

crates/escalier_ast/src/identifier.rs, crates/escalier_ast/src/literal.rs, crates/escalier_ast/src/type_ann.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_pattern.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_var_decls-4.snap, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/type_ann_parser.rs
We only track the mutability of bindings.  Checks are done when inferring `let` statements and unifying function calls.  In the future we'll also check non-let assignments, e.g. `a.x = "foo"`.
TODO:
=> Add proper mutability checking

crates/escalier_ast/src/expr.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_conditionals.snap, crates/escalier_parser/src/type_ann_parser.rs
This works at both the expression level and the type level.
=> If-else chaining

crates/escalier_hm/src/infer.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_type_alias-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_conditional_type.snap, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/type_ann_parser.rs
This PR also makes a minor to how we infer conditional types to preference new type aliases without them leaking out of the conditional type into the surrounding context.
=> use ':' instead of 'extends' everywhere

crates/escalier_ast/src/type_ann.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_tuple_types-3.snap, crates/escalier_parser/src/type_ann_parser.rs
This PR updates the parser to handle rest elements in tuple types and updates `unify()` to handle unifying functions that have rest elements.  It also allows unification of `..._` in a param list with any number of params.  This is used in utility types such as `Parameters<T>` which returns the type of each parameter inside a tuple.
=> Initial support for rest elements in tuple types

crates/escalier_hm/src/context.rs, crates/escalier_hm/src/folder.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/key_value_store.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_hm/tests/exceptions_test.rs
This PR also updates the `Visitor` in `escalier_hm` to follow the same pattern as the one in `escalier_ast`.
=> Add 'Folder' to replace old types 'Visitor' for most use cases

crates/escalier_ast/src/type_ann.rs, crates/escalier_hm/src/checker.rs, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_pattern.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/exceptions_test.rs, crates/escalier_hm/tests/integration_test.rs
This PR introduces a `Checker` struct and makes a bunch of functions that were taking `arena` as a param to be methods on `Checker`.  This simplifies calls to those methods.  It also will make recoverable error handling easier in the future because we can store the diagnostics on `Checker` instead of having to pass them around as params to everything.
=> Add Checker struct and make existing functions methods on it

Cargo.lock, Cargo.toml, crates/escalier_ast/Cargo.toml, crates/escalier_ast/src/class.rs, crates/escalier_ast/src/expr.rs, crates/escalier_ast/src/identifier.rs, crates/escalier_ast/src/literal.rs, crates/escalier_codegen/Cargo.toml, crates/escalier_codegen/src/d_ts.rs, crates/escalier_codegen/src/js.rs, crates/escalier_codegen/src/lib.rs, crates/escalier_codegen/tests/codegen_test.rs, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/folder.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/jsx_parser.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/pattern_parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_class_with_private_constructor_public_methods.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_object_literals-8.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_type_alias-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_object_types-4.snap, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/type_ann_parser.rs
=> Port escalier_old_codegen to work with new AST and type checker

crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_comments-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_comments.snap, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/token.rs
We need to support parsing comments (even if we just ignore them for now) so that we can support the examples on the demo page.
=> Parse line comments before statements

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_interop/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_keyof.snap, crates/escalier_parser/src/stmt_parser.rs
Constraints on type params can reference other type params.  This PR creates a new `sig_ctx` Context when inferring and expanding type aliases.  We add entries to `sig_ctx.schemes` for each type param where the value is the corresponding type argument.
=> Fix Pick<T, K>

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_interop/tests/integration_test.rs
`Pick<{a?: string, b: number, c: boolean}, "a" | "b">` now returns `{a?: string | undefined, c: number}`.  This behaviour matches TS' behaviour.
=> Maintain property optionality across mapped types

crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/precedence.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-5.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-6.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_assignment-7.snap, crates/escalier_parser/src/type_ann_parser.rs
- add parse_infix() and parse_prefix() methods to expr_parser.rs
- normalize precedence, handle Right associativity, prevent assignment chaining
- update type_ann_parser to mimic changes to expr_parser
=> Refactor precedence handling in parser

crates/escalier_ast/src/expr.rs, crates/escalier_ast/src/visitor.rs, crates/escalier_codegen/src/js.rs, crates/escalier_hm/src/infer.rs, crates/escalier_lsp/src/semantic_tokens.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_class_with_private_constructor_public_methods.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_new-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_new.snap, crates/escalier_parser/src/token.rs
This only handles parsing of `new` expressions.  Type checking will be handled in a separate PR.
=> Parse 'new' keyword for constructing new instances

crates/escalier_ast/src/type_ann.rs, crates/escalier_codegen/src/d_ts.rs, crates/escalier_hm/src/folder.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_interop/src/parse.rs, crates/escalier_interop/src/util.rs, crates/escalier_interop/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_declare_let-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_let_fn_with_fn_type.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_type_alias-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__stmt_parser__tests__parse_var_decls-4.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_fn_type_ann-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_fn_type_ann.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_func_with_rest_param-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_func_with_rest_param-3.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_func_with_rest_param.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_object_type_all_sig_types.snap, crates/escalier_parser/src/type_ann_parser.rs
Call and constructor signatures should be generalized just like any other function signature.
=> Generalize callable (and newable) signatures

crates/escalier_ast/src/class.rs, crates/escalier_ast/src/visitor.rs, crates/escalier_codegen/src/js.rs, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/folder.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_class.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/src/visitor.rs, crates/escalier_hm/tests/exceptions_test.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_interop/src/parse.rs, crates/escalier_interop/src/util.rs, crates/escalier_parser/src/class.rs
This will allow us to use variables whose type is private.  There's still some kinks to work out with type params that reference themselves.
=> Add an (inferred) .scheme field on TypeRefs

crates/escalier_hm/src/infer_class.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_ambiguous_generics.snap
This PR updates the inferred interface (instance scheme) by unifying each method's params and return type with those inferred from the body of each method.
This doesn't handle methods that throw correctly.  I'll do that in a separate PR once I fix an ordering issue with `thows` in regular non-method functions.
=> Better inference of methods in classes
