escalier-lang/escalier

src/codegen.rs, src/lib.rs, tests/codegen_test.rs
This converts `Expr`s to `Strings`.
=> Add initial codegen support

src/infer.rs, src/lib.rs, src/ts/ast.rs, src/ts/convert.rs, src/ts/mod.rs, tests/integration_test.rs
We still don't write anything to disk yet, but this is a step towards being able to output .d.ts files in the future.
=> [codegen]: use Env and Program to generate .d.ts output

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, demo/app.tsx, package.json, src/main.rs, tests/codegen_test.rs, tests/integration_test.rs
Hopefully this is will be a memorable name.
=> Rename project from 'nouveau' to 'beignet'

src/constraint_solver.rs, src/infer.rs, src/js/builder.rs, src/lexer.rs, src/parser.rs, src/syntax.rs, src/ts/ast.rs, src/ts/convert.rs, tests/integration_test.rs
This doesn't support codegen of if-else.  I'll tackle that in a separate PR on the weekend when I have more time.
=> Add initial support for let-rec and if-else

src/infer.rs, tests/integration_test.rs
=> Normalize generic types returned by infer_expr

src/js/builder.rs, tests/codegen_test.rs, tests/integration_test.rs
=> Wrap IIFEs in parentheses

src/infer/constraint_solver.rs, tests/integration_test.rs
=> Support function overloading in declared functions

src/ast/expr.rs, src/ast/types.rs, src/codegen/d_ts.rs, src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/infer/infer_mem.rs, src/infer/substitutable.rs, src/parser/snapshots/crochet__parser__tests__type_decls-2.snap, src/parser/snapshots/crochet__parser__types__tests__type_annotations-3.snap, src/parser/types.rs, src/types.rs, tests/integration_test.rs
=> Add support for optional properties on objects

src/infer/substitutable.rs
This simplifies the Substitutable implementation for `Type` a bit.
=> Add Substitutable impls for Option and TProp

src/infer/constraint_solver.rs, src/infer/context.rs, src/infer/infer.rs, src/types.rs
There's a lot of clean that has to happen after this lands, but I'd like to tackle that in a separate PR.
=> Move to the new infer_pattern implementation

src/infer/constraint_solver.rs, src/infer/infer_expr.rs, src/infer/infer_pattern.rs, src/infer/infer_prog.rs, src/infer/infer_type_ann.rs, tests/integration_test.rs
=> infer scheme with proper qualifiers in infer_prog

src/ast/expr.rs, src/codegen/js.rs, src/infer/context.rs, src/infer/infer_expr.rs, src/parser/expr.rs, src/parser/mod.rs, src/parser/snapshots/crochet__parser__tests__objects-2.snap, src/parser/snapshots/crochet__parser__tests__objects.snap, src/parser/snapshots/crochet__parser__tests__type_annotations-4.snap, tests/integration_test.rs
=> Add support for object shorthand

src/ast/pattern.rs, src/codegen/d_ts.rs, src/codegen/js.rs, src/infer/infer_expr.rs, src/infer/infer_pattern.rs, src/parser/mod.rs, src/parser/pattern.rs, src/parser/snapshots/crochet__parser__tests__if_let-2.snap, src/parser/snapshots/crochet__parser__tests__if_let-3.snap, src/types.rs, tests/integration_test.rs
=> Add basic support for refutable if-let statements

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
=> Implement tuple handling in "no-constraints" algorithm

crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/lib.rs
e.g.
```
declare let a: string | number
let sum = if let x is number = a {
x + 5
}
```
=> Type-checking of if-let patterns containing 'is' patterns

crates/crochet/src/lib.rs
- removed unused code
- update `compile` to return a result
=> Cleanup wasm binding

crates/crochet_ast/src/pattern.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/lit.rs, crates/crochet_parser/src/pattern.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__destructuring-10.snap
I'll handle codegen in a separate PR along with codegen for other patterns.
=> Wildcard patterns (parsing and type inference)

crates/crochet_ast/src/expr.rs, crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/lit.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__numbers-3.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__operations-11.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__operations-12.snap
=> Unary minus

demo/app.tsx, demo/examples.js, index.html
This PR also updates the UI a bit by changing the output dropdown to a set of tabs.
=> Add pattern matching examples

demo/app.tsx, demo/dropdown.tsx, demo/examples.js, demo/util.ts, index.html
=> Add permalinking to demo

crates/crochet/tests/integration_test.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/types/type.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/expr.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__member_access-5.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__member_access-6.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__member_access-7.snap, crates/crochet_parser/src/snapshots/crochet_parser__tests__member_access-8.snap
=> Computed member access

crates/crochet_codegen/src/js.rs, crates/crochet_codegen/tests/codegen_test.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/unify.rs
There are still some issues with it that will require tackling #227 before they can be resolved.
=> Improve partial application codegen

crates/crochet_ast/src/expr.rs, crates/crochet_ast/src/keyword.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_codegen/src/js.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__types-4.snap, crates/crochet_parser/src/type_ann.rs, crates/crochet_types/src/type.rs
=> Lookup methods on arrays and parse 'symbol' in .d.ts files

crates/crochet_dts/src/parse_dts.rs, crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/infer_expr.rs
=> Update arrays/tuples to use TS' ReadonlyArray type definition

crates/crochet_tree_sitter_parser/src/lib.rs, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__async_await-2.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__if_else-2.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__if_else.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__rust_style_functions-2.snap, crates/crochet_tree_sitter_parser/src/snapshots/crochet_tree_sitter_parser__tests__rust_style_functions.snap, crates/tree_sitter_crochet/corpus/expressions.txt, crates/tree_sitter_crochet/corpus/statements.txt, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/grammar.js, crates/tree_sitter_crochet/src/grammar.json, crates/tree_sitter_crochet/src/node-types.json
This allows us to control whether the statement block should "return" a value or not.
=> Insert empty expression if last node in statement block is an expresison

crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/parse_dts.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/unify.rs, crates/crochet_infer/src/util.rs, crates/crochet_types/src/obj.rs, crates/crochet_types/src/type.rs
And update parse_dts.rs to infer the following signatures/types in interfaces in .d.ts files:
=> Add constructor and index object element types

crates/crochet_ast/src/type_ann.rs, crates/crochet_codegen/src/d_ts.rs, crates/crochet_dts/src/util.rs, crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/infer_fn_param.rs, crates/crochet_infer/src/infer_pattern.rs, crates/crochet_infer/src/infer_type_ann.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/substitutable.rs, crates/crochet_infer/src/util.rs, crates/crochet_parser/src/lib.rs, crates/crochet_parser/src/snapshots/crochet_parser__tests__type_decls-10.snap, crates/crochet_types/src/type.rs
This is similar to member access but at the type level.
=> Add support for indexed access types

DESIGN.md, README.md
Describes existing and planned features for the language.
=> Add a DESIGN.md doc

crates/crochet_infer/src/context.rs, crates/crochet_infer/src/infer_expr.rs, crates/crochet_infer/src/key_of.rs, crates/crochet_infer/src/lib.rs, crates/crochet_infer/src/visitor.rs, crates/crochet_parser/src/lib.rs
This PR also requires some other misc cleanup, but the majority of it pertains to the `keyof` implementation.
=> Simplify keyof implementation

crates/crochet/src/lib.rs
The output looks something like this:
```
CompileError
│
╰┬▶ TypeError::TooFewArguments
│  ╰╴ Not enough args provided
│
╰▶ TypeError::UnificationError: "hello", number
╰╴ Unification failure
```
Now that the location information has been removed, we'll be able to use it for output in fixture tests.
NOTE: The locations were for the source of the error within the compiler source code, **not** the code being compiled.
=> Update JavaScript report output to show debug formatting, but the hide Location data

crates/tree_sitter_crochet/corpus/destructuring.txt, crates/tree_sitter_crochet/corpus/tsx/declarations.txt, crates/tree_sitter_crochet/corpus/tsx/expressions.txt, crates/tree_sitter_crochet/grammar.js, design/mvp/01_preliminaries.md, design/mvp/02_expressions.md
This PR reflects changes made in #356.
=> Update expression docs

.gitignore, .vscode/settings.json, clean.sh, package.json
=> Enable running coverage locally

crates/crochet/src/lib.rs, demo/app.tsx, demo/wasm.ts
=> Add tabs for AST and sourcemap to demo

crates/crochet_dts/tests/integration_test.rs, crates/crochet_infer/src/unify.rs
=> Fix the false-y case when using conditional types

crates/escalier_codegen/src/d_ts.rs
I also removed some dead code.
=> Dedupe .d.ts codegen a bit

crates/escalier_ast/src/values/expr.rs, crates/escalier_codegen/src/js.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/update.rs, crates/escalier_lsp/src/semantic_tokens.rs, crates/escalier_lsp/src/visitor.rs
`ExprKind::LetDecl` has superseded `ExprKind::Let`.
=> Remove ExprKind::Let and clean up related code

crates/escalier_ast/src/values/class.rs, crates/escalier_ast/src/values/expr.rs, crates/escalier_ast/src/values/ident.rs, crates/escalier_ast/src/values/jsx.rs, crates/escalier_ast/src/values/lit.rs, crates/escalier_ast/src/values/pattern.rs, crates/escalier_ast/src/values/type_ann.rs, crates/escalier_infer/src/snapshots/escalier_infer__tests__infer_ident_inside_lam.snap, crates/escalier_infer/src/update.rs
This removes a bunch of handwriting traversal code.  It also introduces the first lifetime into the codebase.
=> Update update.rs to use derived visitor

crates/escalier/tests/pass/nested_for_loops.d.ts, crates/escalier/tests/pass/nested_for_loops.esc, crates/escalier/tests/pass/nested_for_loops.js, crates/escalier/tests/pass/nested_for_loops.js.map, crates/escalier_ast/src/values/block.rs, crates/escalier_ast/src/values/class.rs, crates/escalier_ast/src/values/expr.rs, crates/escalier_ast/src/values/mod.rs, crates/escalier_ast/src/values/stmt.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_codegen/src/d_ts.rs, crates/escalier_codegen/src/js.rs, crates/escalier_codegen/tests/.codegen_test.rs.pending-snap, crates/escalier_codegen/tests/codegen_test.rs, crates/escalier_infer/src/context.rs, crates/escalier_infer/src/infer_class.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/lib.rs, crates/escalier_infer/src/snapshots/escalier_infer__tests__infer_ident_inside_lam.snap, crates/escalier_parser/src/lib.rs, crates/escalier_parser/src/snapshots/escalier_parser__tests__for_loops.snap, crates/escalier_parser/src/stmt.rs
=> Add support for 'for-of' loops

crates/escalier_infer/src/expand_type.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/lib.rs, crates/escalier_parser/src/stmt.rs
=> Support multiple returns

crates/escalier/src/lib.rs, crates/escalier/tests/fixture_tests.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_codegen/src/d_ts.rs, crates/escalier_codegen/tests/codegen_test.rs, crates/escalier_infer/src/checker.rs, crates/escalier_infer/src/context.rs, crates/escalier_infer/src/expand_type.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/lib.rs, crates/escalier_infer/src/util.rs, crates/escalier_interop/src/checker.rs, crates/escalier_interop/tests/integration_test.rs
This PR:
- removes unnecessary and/or duplicate methods
- simplifies remaining methods by removing unnecessary logic and deduplicating code by having methods call other methods
=> Simplify Context

Cargo.lock, Cargo.toml, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/lib.rs
This PR modifies the original code (linked to at the top of the file) to support n-ary functions.
=> Start work on new implementation for HM type inference

crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs
I wanted the structure to be a little closer to what we have in `escalier_infer` before continuing to iterate on this reimplementation.
=> Split hm/lib.rs into multiple files refactor data structures

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/types.rs
=> Add Program and Statement nodes

Cargo.lock, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/env.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs, crates/escalier_hm/src/util.rs
I'm also going to create a `Context` struct that encapsulates `env` and `non_generic_type`.
=> Use 'im' crate for Env in escalier_hm

Cargo.lock, crates/escalier_hm/Cargo.toml, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/syntax.rs
=> Update syntax AST to track inferred type

crates/escalier_ast/src/types/provenance.rs, crates/escalier_ast/src/types/type.rs, crates/escalier_ast/src/values/block.rs, crates/escalier_ast/src/values/class.rs, crates/escalier_ast/src/values/expr.rs, crates/escalier_ast/src/values/jsx.rs, crates/escalier_ast/src/values/pattern.rs, crates/escalier_ast/src/values/stmt.rs, crates/escalier_ast/src/values/type_ann.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_codegen/src/d_ts.rs, crates/escalier_codegen/src/js.rs, crates/escalier_infer/src/infer_class.rs, crates/escalier_infer/src/infer_expr.rs, crates/escalier_infer/src/infer_fn_param.rs, crates/escalier_infer/src/infer_pattern.rs, crates/escalier_infer/src/infer_prog.rs, crates/escalier_infer/src/infer_stmt.rs, crates/escalier_infer/src/infer_type_ann.rs, crates/escalier_infer/src/type_error.rs, crates/escalier_infer/src/update.rs, crates/escalier_interop/tests/integration_test.rs, crates/escalier_lsp/src/semantic_tokens.rs, crates/escalier_lsp/src/server.rs, crates/escalier_parser/src/expr.rs, crates/escalier_parser/src/lib.rs, crates/escalier_parser/src/pattern.rs, crates/escalier_parser/src/stmt.rs, crates/escalier_parser/src/type_ann.rs, crates/escalier_parser/src/util.rs
This will allow us to use the values AST from `escalier_ast` in `escalier_hm` in the future.
=> Parameterize values AST from escalier_ast

crates/escalier_hm/src/ast/pattern.rs, crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_pattern.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/src/parser/pattern.rs, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-12.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-13.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-15.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-4.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-5.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-6.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__destructuring-7.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__if_let-2.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__if_let.snap, crates/escalier_hm/src/parser/snapshots/escalier_hm__parser__tests__pattern_matching.snap, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs
Add basic support for pattern matching all pattern types we support.
=> Basic pattern matching in escalier_hm

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/infer_pattern.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/tests/integration_test.rs
=> Replace .name on FuncParam with .pattern

crates/escalier_parser/src/expr.rs, crates/escalier_parser/src/expr_parser.rs, crates/escalier_parser/src/lexer.rs, crates/escalier_parser/src/parser.rs, crates/escalier_parser/src/scanner.rs, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_callback.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_conditionals.snap, crates/escalier_parser/src/snapshots/escalier_parser__expr_parser__tests__parse_literals-6.snap, crates/escalier_parser/src/snapshots/escalier_parser__lexer__tests__lex_nested_template_strings.snap, crates/escalier_parser/src/snapshots/escalier_parser__lexer__tests__lex_nested_template_strings_complex.snap, crates/escalier_parser/src/snapshots/escalier_parser__lexer__tests__lex_template_string.snap, crates/escalier_parser/src/snapshots/escalier_parser__lexer__tests__lex_template_string_with_exprs.snap, crates/escalier_parser/src/stmt_parser.rs, crates/escalier_parser/src/token.rs, crates/escalier_parser/src/type_ann_parser.rs
=> implement string and template string parsing

crates/escalier_parser/src/lexer.rs
This PR removes a lot of duplicate code from the lexer.
=> Cleanup lexer

crates/escalier_hm/src/unify.rs, crates/escalier_hm/tests/integration_test.rs
In particular we now unify properties with getters and methods in immutable object types.
=> Improve obj-obj unification

crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/tests/integration_test.rs
After the recently refactoring of how `mut` works we were no longer calling `unify_mut()`.  This PR fixes that.
=> Actually call unify_mut()

crates/escalier_ast/src/type_ann.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/tests/integration_test.rs, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_conditional_type-2.snap, crates/escalier_parser/src/snapshots/escalier_parser__type_ann_parser__tests__parse_pattern_mathing_type.snap, crates/escalier_parser/src/type_ann_parser.rs
=> Add "match" types

crates/escalier_ast/src/lib.rs, crates/escalier_ast/src/visitor.rs, crates/escalier_hm/src/ast_utils.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/lib.rs, crates/escalier_hm/tests/integration_test.rs
=> Handle multiple returns

crates/escalier_hm/src/context.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/integration_test.rs
- eagerly check type args satisfy constraints on type params and that we have the right number of type args
- eagerly check binary type operands
- dedupe `expand_alias` code
=> Misc cleanup of type param handling code

crates/escalier_codegen/tests/codegen_test.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/src/types.rs, crates/escalier_hm/src/unify.rs, crates/escalier_hm/src/util.rs, crates/escalier_hm/tests/exceptions_test.rs, crates/escalier_hm/tests/integration_test.rs
This finishes up the work needed to address #650.
=> Use TypeKind::Array instead of TypeKind::Constructor for arrays

crates/escalier_hm/src/unify.rs, crates/escalier_hm/tests/integration_test.rs
This finishes the work to close #653.
=> Handle tuples as rest args

Cargo.lock, crates/escalier_cli/Cargo.toml, crates/escalier_cli/tests/codegen_test.rs, crates/escalier_cli/tests/integration_test.rs, crates/escalier_hm/src/infer.rs, crates/escalier_hm/tests/integration_test.rs
This will allow us to finally get rid of tree-sitter.  There's a number of tests that need to be fixed, but I'll be tackling that in subsequent PRs because there's already a lot of changes in this one.
=> Update escalier_cli to use new crates

Cargo.lock, crates/escalier_ast/src/visitor.rs, crates/escalier_lsp/Cargo.toml, crates/escalier_lsp/src/main.rs, crates/escalier_lsp/src/semantic_tokens.rs, crates/escalier_lsp/src/server.rs, crates/escalier_lsp/src/util.rs
This is the very last thing that needed to be updated before we can get rid of tree-sitter and the old crates.
=> Update escalier_lsp to use new crates
